---
app_name: Inferno
base_path: inferno
purge_database_on_reload: false
disable_verify_peer: false
bind: 0.0.0.0
disable_tls_tests: false
default_scopes: launch launch/patient offline_access openid profile user/*.* patient/*.*
log_level: unknown
log_to_file: false
logging_enabled: true
autorun_capability: false
include_extras: true
badge_text: Community
resource_validator: external
external_resource_validator_url: http://validator_service:4567
modules:
- smart
- demo_module
presets:
  site_healthit_gov:
    name: SITE DSTU2 FHIR Sandbox
    uri: https://fhir.sitenv.org/secure/fhir
    module: onc
    inferno_uri: https://inferno.healthit.gov
    client_id: vkPKDPcTIEMaw5Uf-DdUUtNMFMZaX0
    confidential_client: true
    client_secret: LS1nY3JFU3FDeEs0cWoxQWF6TVJFNU05RmZZNGZhZ2Vwb2JYWjdSWWJGakwwNTZ2Vng=
    instructions: https://github.com/onc-healthit/inferno/wiki/SITE-Preset-Instructions
  site_test_healthit_gov:
    name: SITE DSTU2 FHIR Sandbox
    uri: https://fhir.sitenv.org/secure/fhir
    module: onc
    inferno_uri: https://infernotest.healthit.gov
    client_id: TrToU5piE-dJ1g6PBG1elFV4r9KLmH
    confidential_client: true
    client_secret: ckFqb1ZhbmFMQS13WDE0c1dTLWxSdGRLSE8yUXpWNS1vSnd6azNrMmU3Y0JPdDRja3U=
    instructions: https://github.com/onc-healthit/inferno/wiki/SITE-Preset-Instructions
  site_local:
    name: SITE DSTU2 FHIR Sandbox
    uri: https://fhir.sitenv.org/secure/fhir
    module: onc
    inferno_uri: http://localhost:4567
    client_id: Yg0o6sJ8I8CfVVyHz1eA0m8jv6sXwe
    confidential_client: true
    client_secret: UDVrTXlna0NvcGRQZ1VhMkZaZzQ0R1FxVGdtTWxFMXVoT3pPd1VRMUN4MFVkV25Gejk=
    instructions: https://github.com/onc-healthit/inferno/wiki/SITE-Preset-Instructions
  standalone_bulk_server_local:
    name: SMART Bulk Server Tests
    module: bdt
    uri: https://bulk-data.smarthealthit.org/eyJlcnIiOiIiLCJwYWdlIjoxMDAwLCJkdXIiOjEwLCJ0bHQiOjE1LCJtIjoxLCJzdHUiOjR9/fhir
    inferno_uri: http://localhost:4567
    bulk_url: https://bulk-data.smarthealthit.org/eyJlcnIiOiIiLCJwYWdlIjoxMDAwLCJkdXIiOjEwLCJ0bHQiOjE1LCJtIjoxLCJzdHUiOjR9/fhir
    bulk_token_endpoint: https://bulk-data.smarthealthit.org/auth/token
    bulk_requires_auth: true
    bulk_client_id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InJlZ2lzdHJhdGlvbi10b2tlbiJ9.eyJqd2tzIjp7ImtleXMiOlt7Imt0eSI6IkVDIiwiY3J2IjoiUC0zODQiLCJ4IjoidFZ6RFdRNXFNMWVrUmtPOWFjVjJPckRXX0p5ZVM2YmFEclhQczl2UE9HT3hhNXo1NUNXdHB3Z19CRHlPWXQ4biIsInkiOiJocFhJQ1pNTmV6RDFvTU5ha09xbEdOaDNXUWdDZEtmUVVwRE5saHhfZEtRbzB5bU1QZVhLeGlzTW1WcVdPay1MIiwia2V5X29wcyI6WyJ2ZXJpZnkiXSwiZXh0Ijp0cnVlLCJraWQiOiJjOTUyOWEwYWFlZmE1ZWE2NTlkNjVjNDkzOWVjYTk3NiIsImFsZyI6IkVTMzg0In0seyJrdHkiOiJFQyIsImNydiI6IlAtMzg0IiwiZCI6Im05Z0pxR2FoOEM4LXZtb3M1LTZicDkwMlRQRkdIdmN0VUl6R2QyMkxQeUU2bzVEMldFVTFtV0VtNzRsRWV5YlAiLCJ4IjoidFZ6RFdRNXFNMWVrUmtPOWFjVjJPckRXX0p5ZVM2YmFEclhQczl2UE9HT3hhNXo1NUNXdHB3Z19CRHlPWXQ4biIsInkiOiJocFhJQ1pNTmV6RDFvTU5ha09xbEdOaDNXUWdDZEtmUVVwRE5saHhfZEtRbzB5bU1QZVhLeGlzTW1WcVdPay1MIiwia2V5X29wcyI6WyJzaWduIl0sImV4dCI6dHJ1ZSwia2lkIjoiYzk1MjlhMGFhZWZhNWVhNjU5ZDY1YzQ5MzllY2E5NzYiLCJhbGciOiJFUzM4NCJ9XX0sImFjY2Vzc1Rva2Vuc0V4cGlyZUluIjoxNSwiaWF0IjoxNTc0MDQ0MjIyfQ.dkqFAJreUXIfBTESdygmiOBhtepzgcDNJWqI2662m4Q
    bulk_public_key: "{'kty':'EC','crv':'P-384','x':'tVzDWQ5qM1ekRkO9acV2OrDW_JyeS6baDrXPs9vPOGOxa5z55CWtpwg_BDyOYt8n','y':'hpXICZMNezD1oMNakOqlGNh3WQgCdKfQUpDNlhx_dKQo0ymMPeXKxisMmVqWOk-L','key_ops':['verify'],'ext':true,'kid':'c9529a0aaefa5ea659d65c4939eca976','alg':'ES384'}"
    bulk_private_key: "{'kty':'EC','crv':'P-384','d':'m9gJqGah8C8-vmos5-6bp902TPFGHvctUIzGd22LPyE6o5D2WEU1mWEm74lEeybP','x':'tVzDWQ5qM1ekRkO9acV2OrDW_JyeS6baDrXPs9vPOGOxa5z55CWtpwg_BDyOYt8n','y':'hpXICZMNezD1oMNakOqlGNh3WQgCdKfQUpDNlhx_dKQo0ymMPeXKxisMmVqWOk-L','key_ops':['sign'],'ext':true,'kid':'c9529a0aaefa5ea659d65c4939eca976','alg':'ES384'}"
    bulk_fastest_resource: Patient
    bulk_system_export_endpoint: "/$export"
    bulk_patient_export_endpoint: "/Patient/$export"
    bulk_group_export_endpoint: "/Group/5/$export"
